### ISSUE TITLE
PA Review: User Authentication

### ISSUE THREAD

**Issue by bucknermr** [bucknermr/soundstorm#1]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate seeding

**Comment by chungkikelly** [comment]
Sign-up errors appear in the `Create Account` button. I think the errors were probably styled for a slightly smaller screen. Although your site doesn't need to be fully responsively-styled, I think this could be a quick fix.
